export default {
	USER_GET_DATA : 'USER_GET_DATA',
	USER_GET_DATA_SUCCESS : 'USER_GET_DATA_SUCCESS',
	USER_GET_DATA_FAIL : 'USER_GET_DATA_FAIL',
	USER_CHANGE_ID : 'USER_CHANGE_ID',

	IMG_RELOAD : 'IMG_RELOAD',
	IMG_RELOAD_SUCCESS : 'IMG_RELOAD_SUCCESS',
	IMG_RELOAD_FAIL : 'IMG_RELOAD_FAIL',
}